### PR TITLE
TECHNICAL WRITING ON  CLOUD COMPUTING (MADE BY GURNOOR KAUR) 

### PR DESCRIPTION
**Pull request by Gurn-k**
Screenshot (14)
Technical writing on topic: Cloud Computing 
Name:Gurnoor Kaur
Username:Gur-k
please review

### CODE REVIEW

**Comment by captain-sal** [comment]
Hey @Gurn-k , it would be better if you will attach the google doc for the same.

**Comment by Gurn-k** [comment]
https://1drv.ms/w/s!AlL7ZTrlQ_PXgQTgrRat9ud1Waze?e=yO7Jau

hello @captain-sal i have attached the link for the word document but it is showing only the text wriiten,it is showing  the link mentioned for the images and the hashtags and asterisk used for editing the text

**Comment by captain-sal** [comment]
@Gurn-k kindly add the images properly and format the text, thanks.

**Comment by Gurn-k** [comment]
Screenshot (15)
Screenshot (16)
Screenshot (17)

i have formatted the text and added pictures in the codespace but im not able to copy the exact formatting of text and pictures to word document

**Comment by Gurn-k** [comment]
https://docs.google.com/document/d/1oBEb8unSZ7yDcSpqNmcbdSucnr3C8vYdT1FS7JFhaF0/edit?usp=sharing
@captain-sal I hv attached the link of google doc

**Pull request merged**
