### PR TITLE
DONE: Write a simple documentation on Cloud Computing #1

### PR DESCRIPTION
**Pull request by Karnankita04**
image

### CODE REVIEW

**Comment by captain-sal** [comment]
Hey @Karnankita04 , please attach the link to the google document.

**Comment by Karnankita04** [comment]
hey @captain-sal I want to confirm one thing, is it like we have to write the documentation in google doc and then attach the link of the doc file here in PR ??

**Comment by captain-sal** [comment]
Hey @Karnankita04, we want you to create a markdown file with extension ".md" and then make the pull request.

**Comment by Karnankita04** [comment]
> Hey @Karnankita04, we want you to create a markdown file with extension ".md" and then make the pull request.

I made the file with name cloud_computing.md and wrote the documentation in it and then made the PR.. 

I am sorry, but I am a little bit confused..

**Comment by captain-sal** [comment]
Yeah, I think there was some confusion at my end.
Merging your PR :)

**Pull request merged**
